# Generated by Django 5.2.9 on 2025-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_event',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Image'),
        ),
    ]
